### ISSUE TITLE
Update the README to provide user instructions for installation

### ISSUE THREAD

**Issue by paladp** [inTestiGator/pytest-blame#31]
# Description of the Issue
We need to update the README once the authentication tokens have been integrated into the plugin. This update should clearly describe to the user what they need to do in order to give our plugin access to their token. This includes steps that describe the creation of said token, and where in their files they should place it.

**Comment by quigley-c** [comment]
The current README is out of date as well, as we currently use `pipenv run pytest --track` to run the plugin.

**Comment by Lancasterwu** [comment]
This issue should be combined with issue #28
